name: Build + Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy_to_bunny:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'

      - name: Yarn Install
        run: yarn install --frozen-lockfile --ignore-optional

      - name: Add dependency 
        run: yarn add @tailwindcss/oxide-linux-x64-gnu

      - name: Build
        run: yarn build

      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.5
        with:
          source: "content"
          destination: "."
          storageZoneName: "${{ secrets.STORAGE_NAME }}"
          storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
          accessKey: "${{ secrets.STORAGE_KEY }}"
          pullZoneId: "${{ secrets.ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"
